### ISSUE TITLE
GenerateSeparateFiles=true leaves an #endregion in IDBContext file.

### ISSUE THREAD

**Issue by HammadRazaKhan** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#290] opened 2017-05-30 14:50 UTC
"#region unit of work" end region is not removed while generating separate files. 
solution:
file: EF.Reverse.POCO.ttinclude
fix:
```
if(ElementsToGenerate.HasFlag(Elements.UnitOfWork) && !string.IsNullOrWhiteSpace(DbContextInterfaceName)) { 
    if(!GenerateSeparateFiles)
        {
#>
    #endregion
<# 
        }
    }
    if(ElementsToGenerate.HasFlag(Elements.Context)){
    fileManager.StartNewFile(DbContextName + FileExtension); #>
<# if(!GenerateSeparateFiles) { #>
    #region Database context
```

**Comment by sjh37** [comment] 2017-05-30 16:43
Thanks.
Duplicate of #287

**Closed as completed by sjh37** 2017-05-30 16:43 UTC
