### ISSUE TITLE
Database.tt Not updating datbase.cs in an asp.net core class library project

### ISSUE THREAD

**Issue by ahmedhassieb** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#261] opened 2017-04-25 10:15 UTC
Hi Simon,

I downloaded the source code and updated my project to a class library .net core project and nothing is generated when I save the Database.tt file. I tried a couple of times to save and run the TT file but with luck.
please help my current version is v2.28.0

**Comment by sjh37** [comment] 2017-04-25 17:10
Duplicate of #5

**Closed as completed by sjh37** 2017-04-25 17:10 UTC
