### ISSUE TITLE
.net Core support

### ISSUE THREAD

**Issue by ahakobyan** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#322] opened 2017-08-21 18:34 UTC
Any updates about EF.Core support or do you have any preliminary estimation of EF Core Reverse POCO version ?

**Comment by yoesak** [comment] 2017-08-26 16:12
For Entity Framework Core v 2.0, you can add this line to your .csproj file:

```
<ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.0" />
  </ItemGroup>
  
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
  </ItemGroup>

```
and then in your command prompt, you can go to your project folder, and type this line

`dotnet restore`

then 

`dotnet ef dbcontext scaffold "Server=<yoursqlserver>;Database=<yourdatabase>;User ID=<yourdatabaseuser>;Password=<yourdatabasepassword>;" Microsoft.EntityFrameworkCore.SqlServer --output-dir Models`

**Comment by sjh37** [comment] 2017-08-31 12:47
I'm closing this as its a duplicate of #5 
Sorry guys, I need to pull my finger out and get it done.

**Closed as completed by sjh37** 2017-08-31 12:47 UTC
Labels: duplicate
