### ISSUE TITLE
Support for .NET Core please

### ISSUE THREAD

**Issue by nrogoff** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#200] opened 2017-01-24 18:40 UTC
Would be great to have .NET Core support for this excellent tool.

**Comment by ErikEJ** [comment] 2017-01-24 20:13
Possible duplicate of https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/issues/5

**Comment by sjh37** [comment] 2017-01-25 09:44
Yes, this is a duplicate of #5 so will close this issue.

**Closed as completed by sjh37** 2017-01-25 09:44 UTC
