### ISSUE TITLE
Excluding columns contain within BaseEntity

### ISSUE THREAD

**Issue by nick5454** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#699] opened 2021-06-10 19:25 UTC
We have 2 columns in every table "CreatedAt" and "UpdatedAt". I put these in BaseEntity.cs.

I don't want to create a column if my BaseEntity.cs class already contains the column.

How could I exclude these columns in all tables if they are in BaseEntity?

**Comment by sjh37** [comment] 2021-06-11 09:44
Duplicate of #698

**Closed as completed by sjh37** 2021-06-11 09:44 UTC
