### ISSUE TITLE
HierarchyId in stored procs - wrong namespace

### ISSUE THREAD

**Issue by m1dst** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#132] opened 2016-10-19 16:28 UTC
When using 2.24.0 and generating against a DB with SqlHierarchyId the wrong namespace is selected for the type (but only when reviewing SPs)

When the table is generated System.Data.Entity.Hierarchy.HierarchyId is the selected type. Good!
When run against a SP containing a HierarchyId it selects System.SqlHierarchyId which doesn't exist.  Bad!

Is this a bug or config issue at my end?

**Comment by sjh37** [comment] 2016-10-24 08:54
Have a read of https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/HierarchyId

If that doesn't help, try referencing:
**Namespace:**   Microsoft.SqlServer.Types
**Assembly:**  Microsoft.SqlServer.Types (in Microsoft.SqlServer.Types.dll)
More info: https://msdn.microsoft.com/en-us/library/microsoft.sqlserver.types.sqlhierarchyid.aspx

See if that helps. Please let me know what worked for you, and I can update the Wiki page. If it doesn't, please let me know and I'll dig further into it for you.

**Comment by m1dst** [comment] 2016-10-24 15:37
I'd tried installing that nuget package prior to reporting the issue.  Made no difference I'm afraid.

**Comment by L1tR05** [comment] 2017-01-27 22:47
The problem is in the file EF.Reverse.POCO.Core.ttinclude

In the definition of function WriteStoredProcReturnColumn, the namespace "System." is hardcoded...

**Comment by L1tR05** [comment] 2017-01-27 22:47
As a workaround, I changed the line:

StoredProcedure.WrapTypeIfNullable("System." + col.DataType.Name,col), col.ColumnName);

To:

StoredProcedure.WrapTypeIfNullable((col.DataType.Name.Equals("SqlHierarchyId")?"Microsoft.SqlServer.Types.":"System.") + col.DataType.Name,col), col.ColumnName);

**Comment by m1dst** [comment] 2017-01-28 16:42
This fix worked nicely.

**Comment by sjh37** [comment] 2017-01-28 18:27
Thanks @L1tR05 !!
I have incorporated this into the generator and will be in the next version

**Closed as completed by sjh37** 2017-01-28 18:27 UTC
Labels: bug
