### ISSUE TITLE
Is there a .NET Core/EF Core version of this tool?

### ISSUE THREAD

**Issue by dfarrNTST** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#341] opened 2017-10-28 16:08 UTC
I really like the flexibility of using this tool, but we have moved to NETStandard and .NET Core...the code generated by this tool does not work with those projects.  Are you working on or have created a version that supports those?

Thanks!

**Comment by ErikEJ** [comment] 2017-10-29 06:44
Duplicate of #5

**Comment by sjh37** [comment] 2017-10-30 10:04
Hi. Sorry no not yet. I want to create it, and its on my todo list, however I've not started it yet. I'm closing this due to being a duplicate of #5

**Closed as completed by sjh37** 2017-10-30 10:04 UTC
