### ISSUE TITLE
Namespace for SqlGeography is generated incorrectly in Stored Procedure return model

### ISSUE THREAD

**Issue by kenlefeb** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#98] opened 2016-08-23 14:20 UTC
I have a stored procedure that returns a DbGeography value. The table entity is correctly generated with the System.Data.Entity.Spatial namespace, but the return model for my stored procedure is generating System.DbGeography? (nullable).

**Comment by L1tR05** [comment] 2017-02-02 05:57
This is related to issue #132

**Comment by sjh37** [comment] 2017-02-03 00:11
This might be also related to #213 which is also fixed, but still pending release.

**Comment by mdentremont** [comment] 2018-04-04 19:52
I can confirm that the issue is still present on the latest build - which includes #132 and #213

**Comment by mdentremont** [comment] 2018-04-05 17:06
NVM - I think we're OK on this front, I was running into a different issue

**Comment by sjh37** [comment] 2018-04-09 14:53
This will be in the next release.

**Closed as completed by sjh37** 2018-04-09 14:53 UTC
Labels: bug
