### ISSUE TITLE
Duplicated Definition of Primary Keys EF6

### ISSUE THREAD

**Issue by kcadduk** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#639] opened 2020-09-23 14:14 UTC
With this table in the database, running the tool, 

```sql
CREATE TABLE [dbo].[ApprovedStatus](
	[Status] [nvarchar](10) NOT NULL,
	[Description] [nvarchar](50) NOT NULL,
	[GUID] [varbinary](16) NOT NULL,
	[RecordTimeStampCreated] [datetime] NOT NULL,
	[RecordLocked] [bit] NOT NULL,
	[Closed] [bit] NOT NULL,
	[ReadOnly] [bit] NOT NULL,
	[RecordTimeStamp] [datetime] NOT NULL,
	[Version] [timestamp] NOT NULL,
	[ID] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_tmpApprovedStatus] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
```

Creates a Model 
``` cs
public partial class ApprovedStatus
    {
        public string Status { get; set; } // Status (length: 10)
        public string Description { get; set; } // Description (length: 50)
        public byte[] GUID { get; set; } // GUID (length: 16)
        public DateTime RecordTimeStampCreated { get; set; } // RecordTimeStampCreated
        public bool RecordLocked { get; set; } // RecordLocked
        public bool Closed { get; set; } // Closed
        public bool ReadOnly { get; set; } // ReadOnly
        public DateTime RecordTimeStamp { get; set; } // RecordTimeStamp
        public byte[] Version { get; set; } // Version (length: 8)
        public int ID { get; set; } // ID (Primary key)

        public sApprovedStatus()
        {
            Status = "";
            Description = "";
            RecordTimeStampCreated = DateTime.UtcNow;
            RecordLocked = false;
            Closed = false;
            ReadOnly = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }
```
and Config File

```cs
 public partial class ApprovedStatusConfiguration : EntityTypeConfiguration<ApprovedStatus>
    {
        public ApprovedStatusConfiguration()
            : this("dbo")
        {
        }

        public ApprovedStatusConfiguration(string schema)
        {
            ToTable("ApprovedStatus", schema);
            HasKey(x => x.ID);

            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("nvarchar").IsRequired().HasMaxLength(10);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.GUID).HasColumnName(@"GUID").HasColumnType("varbinary").IsRequired().HasMaxLength(16);
            Property(x => x.RecordTimeStampCreated).HasColumnName(@"RecordTimeStampCreated").HasColumnType("datetime").IsRequired();
            Property(x => x.RecordLocked).HasColumnName(@"RecordLocked").HasColumnType("bit").IsRequired();
            Property(x => x.Closed).HasColumnName(@"Closed").HasColumnType("bit").IsRequired();
            Property(x => x.ReadOnly).HasColumnName(@"ReadOnly").HasColumnType("bit").IsRequired();
            Property(x => x.RecordTimeStamp).HasColumnName(@"RecordTimeStamp").HasColumnType("datetime").IsRequired();
            Property(x => x.Version).HasColumnName(@"Version").HasColumnType("timestamp").IsRequired().IsFixedLength().HasMaxLength(8).IsRowVersion();
            Property(x => x.ID).HasColumnName(@"ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);

            InitializePartial();
        }

        partial void InitializePartial();
    }
```

However, in the context, it also defines the Primary Key as an Index.

```cs
 // Indexes        
            modelBuilder.Entity<ApprovedStatus>()
                .Property(e => e.ID)
                .HasColumnAnnotation(
                    IndexAnnotation.AnnotationName,
                    new IndexAnnotation(new IndexAttribute("PK_ApprovedStatus", 1) { IsUnique = true, IsClustered = true })
                );
```

When I try to call Database.CreateIfNotExists() i get an exception

```
 System.Data.SqlClient.SqlException: Cannot create more than one clustered index on table 'dbo.ApprovedStatus'. Drop the existing clustered index 'PK_dbo.ApprovedStatus' before creating another.
```

If I comment out the index declaration in the Context, it creates the table (with a Primary Key). 

Am I missing something?

**Comment by sjh37** [comment] 2020-09-23 16:29
Hi, that index should not be created. What version of the generator is this with?

**Comment by sjh37** [comment] 2020-09-23 16:33
This is a duplicate of #587
The bug has been fixed, but not yet released. 
For now, grab the latest code from [GitHub EF.Reverse.POCO.v3.ttinclude](https://raw.githubusercontent.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/ef6d10789216af4e3280ce64069a207c81b9c08c/EntityFramework.Reverse.POCO.Generator/EF.Reverse.POCO.v3.ttinclude)

**Closed as completed** 2020-09-23 17:13 UTC
