### ISSUE TITLE
"partial" modifier incorrectly placed for FakeQueryProvider<T>

### ISSUE THREAD

**Issue by slee-accesso** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#718] opened 2021-09-03 17:43 UTC
The output ends up being something like this:
```
public partial abstract class FakeQueryProvider<T> : IOrderedQueryable<T>, IQueryProvider
```
But the compile error you get is:  
```
CS0267: The 'partial' modifier can only appear immediately before 'class', 'record', 'struct', 'interface', or a method return type.
```
So - it looks like maybe you need to either dump the abstract modifier - or place it first in the ttinclude file. I changed this:
```
{{DbContextClassModifiers}} abstract class FakeQueryProvider<T> : IOrderedQueryable<T>, IQueryProvider{{#newline}}
```
to this
```
abstract {{DbContextClassModifiers}} class FakeQueryProvider<T> : IOrderedQueryable<T>, IQueryProvider{{#newline}}
```
in both locations in the ttinclude, and it generated the code without causing compile errors. 

  Cheers!

**Comment by sjh37** [comment] 2022-02-14 17:34
Duplicate of #692

**Closed as completed by sjh37** 2022-02-14 17:34 UTC
