### ISSUE TITLE
CS0103 "The name 'NorthwindDbContextStaticPartial' does not exist in the current context" if MakeClassesPartial = true

### ISSUE THREAD

**Issue by vLGrok** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#175] opened 2016-12-28 21:10 UTC
> Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'NorthwindDbContextStaticPartial' does not exist in the current context	NwDemo	E:\git\stuff\NwDemo\NwDemo\Databases\Northwind\NorthwindDbContext.cs	37	Active

Version 2.26.0
Changing only the one setting, running custom tool, then building project causes the above exception.
Changing it back to false, saving, and building eliminates the exception.

What can I do differently?

**Comment by vLGrok** [comment] 2016-12-28 21:11
```C#
`<#@ include file="..\EF.Reverse.POCO.Core.ttinclude" #>
<#
    // v2.26.0
    // Please make changes to the settings below.
    // All you have to do is save this file, and the output file(s) is/are generated. Compiling does not regenerate the file(s).
    // A course for this generator is available on Pluralsight at https://www.pluralsight.com/courses/code-first-entity-framework-legacy-databases

    // Main settings **********************************************************************************************************************
    ConnectionStringName = "Northwind";   // Searches for this connection string in config files listed below in the ConfigFilenameSearchOrder setting
    //ConnectionStringName is the only required setting
    // Namespace = ""; // Override the default namespace here
    DbContextName = "NorthwindDbContext";
    //DbContextInterfaceName = "IMyDbContext"; //Defaults to "I" + DbContextName
    DbContextInterfaceBaseClasses = "System.IDisposable";    // Specify what the base classes are for your database context interface
    DbContextBaseClass = "System.Data.Entity.DbContext";   // Specify what the base class is for your DbContext. For ASP.NET Identity use "IdentityDbContext<ApplicationUser>"
    //DefaultConstructorArgument = "EnvironmentConnectionStrings.MyDbContext"; //defaults to "Name=" + ConnectionStringName
    TargetFrameworkVersion = "4.52"; // Please set this to your .NET framework version, 4.0, 4.5, 4.51, etc.
    ConfigurationClassName = "Configuration"; // Configuration, Mapping, Map, etc. This is appended to the Poco class name to configure the mappings.
    ConfigFilenameSearchOrder = new[] { "app.config", "web.config", "app.config.transform", "web.config.transform" }; // Add more here if required. The config files are searched for in the local project first, then the whole solution second.
    MakeClassesPartial = true;
    MakeDbContextInterfacePartial = false;
    GenerateSeparateFiles = true;
    UseMappingTables = true; // If true, mapping will be used and no mapping tables will be generated. If false, all tables will be generated.
    UsePascalCase = true;    // This will rename the generated C# tables & properties to use PascalCase. If false table & property names will be left alone.
    UseDataAnnotations = false; // If true, will add data annotations to the poco classes.
    UseDataAnnotationsSchema = false; // UseDataAnnotations must also be true. If true, will add data annotations schema to the poco classes.
    IncludeComments = CommentsStyle.AtEndOfField; // Adds comments to the generated code
    IncludeExtendedPropertyComments = CommentsStyle.InSummaryBlock; // Adds extended properties as comments to the generated code
    IncludeViews = false;
    IncludeSynonyms = false;
    IncludeStoredProcedures = false;
    IncludeTableValuedFunctions = false; // If true, you must set IncludeStoredProcedures = true, and install the "EntityFramework.CodeFirstStoreFunctions" Nuget Package.
    DisableGeographyTypes = true; // Turns off use of System.Data.Entity.Spatial.DbGeography and System.Data.Entity.Spatial.DbGeometry as OData doesn't support entities with geometry/geography types.
    CollectionType = "System.Collections.Generic.List";  // Determines the type of collection for the Navigation Properties. "ObservableCollection" for example. Add "System.Collections.ObjectModel" to AdditionalNamespaces if setting the CollectionType = "ObservableCollection".
    NullableShortHand = true; //true => T?, false => Nullable<T>
    AddUnitTestingDbContext = false; // Will add a FakeDbContext and FakeDbSet for easy unit testing
    IncludeQueryTraceOn9481Flag = false; // If SqlServer 2014 appears frozen / take a long time when this file is saved, try setting this to true (you will also need elevated privileges).
    IncludeCodeGeneratedAttribute = true; // If true, will include the GeneratedCode attribute, false to remove it.
    UsePrivateSetterForComputedColumns = true; // If the columns is computed, use a private setter.
    AdditionalNamespaces = new[] { "System" };  // To include extra namespaces, include them here. i.e. "Microsoft.AspNet.Identity.EntityFramework"
`

**Comment by ErikEJ** [comment] 2016-12-29 06:55
Duplicate of https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/issues/155 ?

**Comment by vLGrok** [comment] 2016-12-29 14:13
Yes. Time to finish the pluralsight course.  ;-p

**Comment by sjh37** [comment] 2016-12-30 00:30
Thanks @ErikEJ

**Closed as completed by sjh37** 2016-12-30 00:30 UTC
